# Generated by Django 3.2 on 2021-04-21 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('created_on', models.DateField(auto_now=True)),
                ('due_on', models.DateField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='TaskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('done', models.BooleanField(default=False)),
                ('task', models.ManyToManyField(to='tasker.Task')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='department',
            field=models.ManyToManyField(to='tasker.Department'),
        ),
    ]
