# Generated by Django 3.2 on 2021-04-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0002_auto_20210421_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_on',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='description',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
