# Generated by Django 3.2 on 2021-04-25 10:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0004_alter_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='head',
        ),
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
